### ISSUE TITLE
Proxy for RTSP bug

### ISSUE THREAD

**Issue by echads** [gabbersepp/victure-camera-cloud#2]
https://github.com/cjlarose/victure-pc540-proxy

I haven't tested it.

Though judging by comment at end, perhaps you knew about it.
"The easiest and best would have been to use ffmpeg. But I (and others in the internet) had no success. It worked only with RTSP Proxies or VLC."

**Comment by gabbersepp** [comment]
Hi,
after a complete new installation of my servers, I tried the camera stuff again.
I was able to access the stream through homeassistant without proxy and also was able to stream the camera to a file using ffmpeg.
